# Generated by Django 4.2.1 on 2023-05-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id_administrator', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nume_utilizator', models.TextField(unique=True)),
                ('hash_parola', models.TextField()),
                ('nume_complet', models.TextField()),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.TextField(unique=True)),
                ('cnp', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume_utilizator', models.CharField(max_length=30)),
                ('hash_parola', models.CharField(max_length=25)),
                ('nume_complet', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('cnp', models.CharField(blank=True, max_length=13, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facilitate',
            fields=[
                ('id_facilitate', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume', models.TextField()),
            ],
            options={
                'db_table': 'facilitate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.IntegerField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('nr_stele', models.IntegerField()),
                ('adresa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Judet',
            fields=[
                ('id_judet', models.IntegerField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'judet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localitate',
            fields=[
                ('id_localitate', models.IntegerField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'localitate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id_recenzie', models.IntegerField(primary_key=True, serialize=False)),
                ('scor', models.SmallIntegerField()),
                ('text_recenzie', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'recenzie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regiune',
            fields=[
                ('id_regiune', models.IntegerField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'regiune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id_rezervare', models.IntegerField(primary_key=True, serialize=False)),
                ('data_efectuarii', models.DateField(blank=True, null=True)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('pret_total', models.FloatField(blank=True, null=True)),
                ('specificatii', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'db_table': 'rezervare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipCamera',
            fields=[
                ('id_tip_camera', models.AutoField(primary_key=True, serialize=False)),
                ('nr_paturi_duble', models.SmallIntegerField()),
                ('nr_paturi_simple', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tip_camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelAdministrator',
            fields=[
                ('id_hotel', models.OneToOneField(db_column='id_hotel', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotel_administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelFacilitate',
            fields=[
                ('id_hotel', models.OneToOneField(db_column='id_hotel', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotel_facilitate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelTipCamera',
            fields=[
                ('id_hotel', models.OneToOneField(db_column='id_hotel', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hotels.hotel')),
                ('nr_camere', models.SmallIntegerField()),
                ('pret_per_noapte', models.FloatField()),
            ],
            options={
                'db_table': 'hotel_tip_camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RezervareTipCamera',
            fields=[
                ('id_rezervare', models.OneToOneField(db_column='id_rezervare', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hotels.rezervare')),
                ('nr_camere', models.SmallIntegerField()),
                ('pret_per_noapte', models.FloatField()),
            ],
            options={
                'db_table': 'rezervare_tip_camera',
                'managed': False,
            },
        ),
    ]
