# Generated by Django 4.2.1 on 2023-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('is_administrator', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
    ]
