FROM python:3.10.9-buster

WORKDIR /usr/src/app

# Solve OS dependencies
RUN apt update 
RUN apt install -y gcc python3-dev build-essential libpq-dev	

# Copy project files
COPY backend/ebooking/ .


# Copy entrypoint script 
COPY docker/entrypoint_django.sh .

# Solve Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN sed -i -e 's/\r$//' entrypoint_django.sh


ENTRYPOINT ["./docker/entrypoint_django.sh"]
