FROM postgres:15

# Copy the PostgreSQL configuration file
COPY docker/postgres.conf /etc/postgresql/postgresql.conf


# Install pglogical
RUN set -eux; \
    apt-get update; \
    apt-get install -y postgresql-15-pglogical

# Start PostgreSQL
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]