SET search_path = global_hotels;

INSERT INTO judet(
nume, id_regiune)
VALUES ('Tulcea',1),
('Constanta',1),
('Braila',2),
('Ialomita',2),
('Calarasi',2),
('Buzau',2),
('Ilfov',2),
('Bucuresti',2),
('Giurgiu',2),
('Prahova',2),
('Dambovita',2),
('Arges',2),
('Teleorman',2),
('Valcea',3),
('Olt',3),
('Dolj',3),
('Gorj',3),
('Mehedinti',3),
('Timis',4),
('Caras-Severin',4),
('Iasi',5),
('Vaslui',5),
('Galati',5),
('Neamt',5),
('Bacau',5),
('Vrancea',5),
('Harghita',6),
('Covasna',6),
('Bistrita Nasaud',6),
('Mures',6),
('Brasov',6),
('Salaj',6),
('Cluj',6),
('Alba',6),
('Sibiu',6),
('Hunedoara',6),
('Bihor',7),
('Arad',7),
('Maramures',9),
('Satu Mare',9),
('Botosani',8),
('Suceava',8);
COMMIT;