SET search_path = global_hotels;

DELETE FROM hotel;


CALL insereaza_in_hotel('Hotel Privo'::TEXT,4,'Strada Principala, nr 106'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Targu Mures','Mures')::INT,true,true);
CALL insereaza_in_hotel('Conacul Bratescu'::TEXT,4,'Strada Principala, nr 52'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bran','Brasov')::INT,true,false);
CALL insereaza_in_hotel('Transylvanian Inn'::TEXT,3,'Strada Principala, nr 125'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bran','Brasov')::INT,false,false);
CALL insereaza_in_hotel('The Mansion Boutique Hotel'::TEXT,4,'Strada Principala, nr 101'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,false);
CALL insereaza_in_hotel('Ioana Hotel'::TEXT,5,'Strada Principala, nr 75'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sinaia','Prahova')::INT,false,true);
CALL insereaza_in_hotel('Epoque Hotel Relais & Chateaux'::TEXT,5,'Strada Principala, nr 33'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,false);
CALL insereaza_in_hotel('Rosen Villa Sibiu'::TEXT,1,'Strada Principala, nr 140'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sibiu','Sibiu')::INT,false,false);
CALL insereaza_in_hotel('Hotel International Iasi'::TEXT,4,'Strada Principala, nr 84'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Iasi','Iasi')::INT,false,true);
CALL insereaza_in_hotel('IAKI Conference & Spa Hotel'::TEXT,4,'Strada Principala, nr 53'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Constanta','Constanta')::INT,false,false);
CALL insereaza_in_hotel('Republique Hotel'::TEXT,4,'Strada Principala, nr 14'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sibiu','Sibiu')::INT,true,true);
CALL insereaza_in_hotel('Hampton by Hilton Cluj-Napoca'::TEXT,3,'Strada Principala, nr 23'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,false,true);
CALL insereaza_in_hotel('Grand Hotel Continental'::TEXT,5,'Strada Principala, nr 15'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sinaia','Prahova')::INT,false,false);
CALL insereaza_in_hotel('Ana Hotels Sport Poiana Brasov'::TEXT,4,'Strada Principala, nr 59'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,true);
CALL insereaza_in_hotel('Hotel Casa Wagner'::TEXT,3,'Strada Principala, nr 29'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,true);
CALL insereaza_in_hotel('Kismet Dao Hostel'::TEXT,1,'Strada Principala, nr 86'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,false);
CALL insereaza_in_hotel('Transylvania Hostel'::TEXT,1,'Strada Principala, nr 122'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,false,false);
CALL insereaza_in_hotel('Orhieea Residence & Spa'::TEXT,4,'Strada Principala, nr 126'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,true);
CALL insereaza_in_hotel('Casa Rozelor - boutique hotel'::TEXT,4,'Strada Principala, nr 75'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,false);
CALL insereaza_in_hotel('ibis Styles Bucharest City Center'::TEXT,3,'Strada Principala, nr 138'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,true);
CALL insereaza_in_hotel('Kronwell Brasov Hotel'::TEXT,4,'Strada Principala, nr 11'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,false);
CALL insereaza_in_hotel('Akasha Wellness Retreat'::TEXT,3,'Strada Principala, nr 141'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bran','Brasov')::INT,false,false);
CALL insereaza_in_hotel('Hilton Garden Inn Bucharest Old Town'::TEXT,4,'Strada Principala, nr 100'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,false,false);
CALL insereaza_in_hotel('Centrum House Hostel & Bar'::TEXT,1,'Strada Principala, nr 106'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,false);
CALL insereaza_in_hotel('The Spot Cosy Hostel'::TEXT,1,'Strada Principala, nr 25'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,false,false);
CALL insereaza_in_hotel('Belfort Hotel'::TEXT,3,'Strada Principala, nr 147'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,false);
CALL insereaza_in_hotel('Ramada by Wyndham Oradea'::TEXT,4,'Strada Principala, nr 110'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Oradea','Bihor')::INT,true,false);
CALL insereaza_in_hotel('Hotel Christina'::TEXT,4,'Strada Principala, nr 149'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,false);
CALL insereaza_in_hotel('Casa Corona'::TEXT,1,'Strada Principala, nr 32'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,true);
CALL insereaza_in_hotel('JW Marriott Bucharest Grand Hotel'::TEXT,5,'Strada Principala, nr 22'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,true);
CALL insereaza_in_hotel('La Roata'::TEXT,3,'Strada Principala, nr 49'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Gura Humorului','Suceava')::INT,false,false);
CALL insereaza_in_hotel('Caro Hotel'::TEXT,4,'Strada Principala, nr 146'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,false,false);
CALL insereaza_in_hotel('Hadar Chalet'::TEXT,1,'Strada Principala, nr 93'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Buzau','Buzau')::INT,false,true);
CALL insereaza_in_hotel('Hotel Cherica'::TEXT,4,'Strada Principala, nr 137'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Constanta','Constanta')::INT,false,false);
CALL insereaza_in_hotel('Golden Tulip Ana Tower Sibiu'::TEXT,4,'Strada Principala, nr 89'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sibiu','Sibiu')::INT,true,true);
CALL insereaza_in_hotel('Capitolina City Chic Hotel'::TEXT,3,'Strada Principala, nr 97'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,true,true);
CALL insereaza_in_hotel('Casa Lia'::TEXT,1,'Strada Principala, nr 140'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sighisoara','Mures')::INT,false,false);
CALL insereaza_in_hotel('Lol et Lola Hotel'::TEXT,3,'Strada Principala, nr 83'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,false,false);
CALL insereaza_in_hotel('Guesthouse La Despani'::TEXT,2,'Strada Principala, nr 30'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,true);
CALL insereaza_in_hotel('Bella Muzica'::TEXT,3,'Strada Principala, nr 98'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,true);
CALL insereaza_in_hotel('Hilton Garden Inn Bucharest Airport'::TEXT,4,'Strada Principala, nr 63'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Otopeni','Ilfov')::INT,false,true);
CALL insereaza_in_hotel('Rembrandt Hotel'::TEXT,3,'Strada Principala, nr 141'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,false);
CALL insereaza_in_hotel('Hotel Central Park'::TEXT,4,'Strada Principala, nr 67'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sighisoara','Mures')::INT,false,true);
CALL insereaza_in_hotel('Casa Savri'::TEXT,1,'Strada Principala, nr 127'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sighisoara','Mures')::INT,true,true);
CALL insereaza_in_hotel('Hotel Radsor'::TEXT,4,'Strada Principala, nr 47'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Baile Herculane','Caras-Severin')::INT,false,true);
CALL insereaza_in_hotel('Hotel Cismigiu'::TEXT,4,'Strada Principala, nr 58'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,true);
CALL insereaza_in_hotel('Splendid Conference & Spa Hotel'::TEXT,4,'Strada Principala, nr 86'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Constanta','Constanta')::INT,false,true);
CALL insereaza_in_hotel('Taschler Haus'::TEXT,3,'Strada Principala, nr 47'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sighisoara','Mures')::INT,true,true);
CALL insereaza_in_hotel('Mandachi Hotel & Spa'::TEXT,4,'Strada Principala, nr 95'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Suceava','Suceava')::INT,true,true);
CALL insereaza_in_hotel('Fronius Residence'::TEXT,5,'Strada Principala, nr 25'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sighisoara','Mures')::INT,true,false);
CALL insereaza_in_hotel('Armatti Hotel'::TEXT,3,'Strada Principala, nr 46'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,false);
CALL insereaza_in_hotel('Concorde Old Bucharest Hotel'::TEXT,4,'Strada Principala, nr 107'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,false,true);
CALL insereaza_in_hotel('Vila Katharina'::TEXT,4,'Strada Principala, nr 77'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,true);
CALL insereaza_in_hotel('The Village Hotel'::TEXT,1,'Strada Principala, nr 106'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Borsa','Maramures')::INT,false,false);
CALL insereaza_in_hotel('Platinia Hotel'::TEXT,5,'Strada Principala, nr 43'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,true,true);
CALL insereaza_in_hotel('Hotel Central'::TEXT,4,'Strada Principala, nr 50'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Ploiesti','Prahova')::INT,false,false);
CALL insereaza_in_hotel('Vienna House Easy Airport Bucharest'::TEXT,4,'Strada Principala, nr 125'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Otopeni','Ilfov')::INT,false,false);
CALL insereaza_in_hotel('Mercure Bucharest City Center'::TEXT,4,'Strada Principala, nr 67'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,true,true);
CALL insereaza_in_hotel('Hotel Sonnenhof'::TEXT,4,'Strada Principala, nr 147'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Suceava','Suceava')::INT,false,false);
CALL insereaza_in_hotel('Teleferic Grand Hotel'::TEXT,4,'Strada Principala, nr 95'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,false);
CALL insereaza_in_hotel('K+K Hotel Elisabeta'::TEXT,4,'Strada Principala, nr 55'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,false,false);
CALL insereaza_in_hotel('Pensiune Restaurant La Cassa'::TEXT,1,'Strada Principala, nr 123'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Viseu de Sus','Maramures')::INT,true,false);
CALL insereaza_in_hotel('Hostel Boemia'::TEXT,1,'Strada Principala, nr 2'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,true);
CALL insereaza_in_hotel('Golden Tulip Ana Dome'::TEXT,4,'Strada Principala, nr 149'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,false,false);
CALL insereaza_in_hotel('Hotel Christina Plus'::TEXT,4,'Strada Principala, nr 14'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,false,false);
CALL insereaza_in_hotel('Simfonia Boutique Hotel'::TEXT,4,'Strada Principala, nr 139'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Ramnicu Valcea','Valcea')::INT,false,false);
CALL insereaza_in_hotel('JugendStube Hostel Brasov'::TEXT,3,'Strada Principala, nr 23'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,true);
CALL insereaza_in_hotel('UpperHouse'::TEXT,1,'Strada Principala, nr 135'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,true);
CALL insereaza_in_hotel('Casa Luxemburg'::TEXT,3,'Strada Principala, nr 61'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sibiu','Sibiu')::INT,true,false);
CALL insereaza_in_hotel('Pensiunea Ana'::TEXT,1,'Strada Principala, nr 99'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bran','Brasov')::INT,true,false);
CALL insereaza_in_hotel('Hille Guesthouse'::TEXT,1,'Strada Principala, nr 23'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bran','Brasov')::INT,false,false);
CALL insereaza_in_hotel('Babou Maramures'::TEXT,1,'Strada Principala, nr 95'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Borsa','Maramures')::INT,true,false);
CALL insereaza_in_hotel('Casa Elvira'::TEXT,3,'Strada Principala, nr 64'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Eforie','Constanta')::INT,false,false);
CALL insereaza_in_hotel('Amethyst House'::TEXT,3,'Strada Principala, nr 58'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Otopeni','Ilfov')::INT,true,true);
CALL insereaza_in_hotel('Hohe Rinne Paltinis Hotel & Spa'::TEXT,4,'Strada Principala, nr 10'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Fagaras','Brasov')::INT,false,true);
CALL insereaza_in_hotel('Hotel Paradis'::TEXT,4,'Strada Principala, nr 130'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,false,true);
CALL insereaza_in_hotel('Pensiunea Teodora Teleptean'::TEXT,1,'Strada Principala, nr 128'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Viseu de Sus','Maramures')::INT,false,false);
CALL insereaza_in_hotel('Ivana Apart Hotel'::TEXT,3,'Strada Principala, nr 124'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Oradea','Bihor')::INT,false,true);
CALL insereaza_in_hotel('Pensiunea Ioana'::TEXT,3,'Strada Principala, nr 119'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Curtea de Arges','Arges')::INT,true,false);
CALL insereaza_in_hotel('Satu Mare City Hotel'::TEXT,4,'Strada Principala, nr 146'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Satu Mare','Satu Mare')::INT,false,true);
CALL insereaza_in_hotel('Pensiunea Christiana'::TEXT,1,'Strada Principala, nr 130'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Arad','Arad')::INT,true,false);
CALL insereaza_in_hotel('Hotel Arnia'::TEXT,3,'Strada Principala, nr 12'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Iasi','Iasi')::INT,true,true);
CALL insereaza_in_hotel('Parliament Hotel'::TEXT,4,'Strada Principala, nr 117'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,false,true);
CALL insereaza_in_hotel('Levoslav House'::TEXT,4,'Strada Principala, nr 33'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Sibiu','Sibiu')::INT,false,false);
CALL insereaza_in_hotel('Little Texas'::TEXT,4,'Strada Principala, nr 99'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Iasi','Iasi')::INT,false,false);
CALL insereaza_in_hotel('Hotel Escalade Poiana Brasov'::TEXT,4,'Strada Principala, nr 73'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,true);
CALL insereaza_in_hotel('Toparceanu Vila'::TEXT,3,'Strada Principala, nr 84'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,false);
CALL insereaza_in_hotel('Pleiada Boutique Hotel'::TEXT,5,'Strada Principala, nr 59'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Iasi','Iasi')::INT,true,false);
CALL insereaza_in_hotel('Marshal Garden Hotel'::TEXT,5,'Strada Principala, nr 147'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bucuresti','Bucuresti')::INT,false,true);
CALL insereaza_in_hotel('Casa Vacanza Brasov'::TEXT,3,'Strada Principala, nr 50'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,true);
CALL insereaza_in_hotel('Helen Hotel Bacau'::TEXT,4,'Strada Principala, nr 58'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Bacau','Bacau')::INT,false,true);
CALL insereaza_in_hotel('Continental Forum Arad'::TEXT,4,'Strada Principala, nr 21'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Arad','Arad')::INT,true,false);
CALL insereaza_in_hotel('Hotel Select Iasi'::TEXT,4,'Strada Principala, nr 60'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Iasi','Iasi')::INT,true,false);
CALL insereaza_in_hotel('Hotel Coroana Brasovului'::TEXT,3,'Strada Principala, nr 68'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,true,false);
CALL insereaza_in_hotel('Central Plaza Hotel'::TEXT,4,'Strada Principala, nr 22'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Brasov','Brasov')::INT,false,true);
CALL insereaza_in_hotel('Pension Bellagio'::TEXT,4,'Strada Principala, nr 102'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,false,false);
CALL insereaza_in_hotel('Opera Plaza Hotel'::TEXT,5,'Strada Principala, nr 52'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,true,false);
CALL insereaza_in_hotel('Del Corso Hotel'::TEXT,3,'Strada Principala, nr 124'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Timisoara','Timis')::INT,true,true);
CALL insereaza_in_hotel('Casa Muntean'::TEXT,1,'Strada Principala, nr 75'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Viseu de Sus','Maramures')::INT,false,true);
CALL insereaza_in_hotel('Hotel Beyfin'::TEXT,4,'Strada Principala, nr 101'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Cluj Napoca','Cluj')::INT,true,false);
CALL insereaza_in_hotel('Lotus Therm Spa & Luxury Resort'::TEXT,5,'Strada Principala, nr 91'::TEXT,gaseste_id_localitate_cu_nume_si_nume_judet('Baile Herculane','Caras-Severin')::INT,true,true);


SELECT *
FROM hotel;