
--DELETE FROM hotel;
--DELETE FROM localitate;

CALL insereaza_in_localitate('Abrud'::TEXT,34);
CALL insereaza_in_localitate('Adjud'::TEXT,26);
CALL insereaza_in_localitate('Aiud'::TEXT,34);
CALL insereaza_in_localitate('Alba Iulia'::TEXT,34);
CALL insereaza_in_localitate('Alesd'::TEXT,37);
CALL insereaza_in_localitate('Alexandria'::TEXT,13);
CALL insereaza_in_localitate('Agnita'::TEXT,35);
CALL insereaza_in_localitate('Anina'::TEXT,20);
CALL insereaza_in_localitate('Aninoasa'::TEXT,36);
CALL insereaza_in_localitate('Arad'::TEXT,38);
CALL insereaza_in_localitate('Avrig'::TEXT,35);
CALL insereaza_in_localitate('Azuga'::TEXT,10);
CALL insereaza_in_localitate('Babadag'::TEXT,1);
CALL insereaza_in_localitate('Bacau'::TEXT,25);
CALL insereaza_in_localitate('Baia de Arama'::TEXT,18);
CALL insereaza_in_localitate('Baia de Aries'::TEXT,34);
CALL insereaza_in_localitate('Baia Mare'::TEXT,39);
CALL insereaza_in_localitate('Baia Sprie'::TEXT,39);
CALL insereaza_in_localitate('Bals'::TEXT,15);
CALL insereaza_in_localitate('Baraolt'::TEXT,28);
CALL insereaza_in_localitate('Baicoi'::TEXT,10);
CALL insereaza_in_localitate('Baile Govora'::TEXT,14);
CALL insereaza_in_localitate('Baile Herculane'::TEXT,20);
CALL insereaza_in_localitate('Baile Olanesti'::TEXT,14);
CALL insereaza_in_localitate('Bailesti'::TEXT,16);
CALL insereaza_in_localitate('Baile Tusnad'::TEXT,27);
CALL insereaza_in_localitate('Balan'::TEXT,27);
CALL insereaza_in_localitate('Barlas'::TEXT,22);
CALL insereaza_in_localitate('Bocsa'::TEXT,20);
CALL insereaza_in_localitate('Borsec'::TEXT,27);
CALL insereaza_in_localitate('Beclean'::TEXT,29);
CALL insereaza_in_localitate('Beius'::TEXT,37);
CALL insereaza_in_localitate('Beresti'::TEXT,23);
CALL insereaza_in_localitate('Bicaz'::TEXT,24);
CALL insereaza_in_localitate('Bistrita'::TEXT,29);
CALL insereaza_in_localitate('Blaj'::TEXT,34);
CALL insereaza_in_localitate('Boldesti Scaieni'::TEXT,10);
CALL insereaza_in_localitate('Bolintin Vale'::TEXT,9);
CALL insereaza_in_localitate('Borsa'::TEXT,39);
CALL insereaza_in_localitate('Botosani'::TEXT,41);
CALL insereaza_in_localitate('Brad'::TEXT,36);
CALL insereaza_in_localitate('Brasov'::TEXT,31);
CALL insereaza_in_localitate('Braila'::TEXT,3);
CALL insereaza_in_localitate('Breaza'::TEXT,10);
CALL insereaza_in_localitate('Brezoi'::TEXT,14);
CALL insereaza_in_localitate('Bucuresti'::TEXT,8);
CALL insereaza_in_localitate('Budesti'::TEXT,5);
CALL insereaza_in_localitate('Buftea'::TEXT,7);
CALL insereaza_in_localitate('Buhusi'::TEXT,25);
CALL insereaza_in_localitate('Bumbesti Jiu'::TEXT,17);
CALL insereaza_in_localitate('Busteni'::TEXT,10);
CALL insereaza_in_localitate('Buzias'::TEXT,19);
CALL insereaza_in_localitate('Buzau'::TEXT,6);
CALL insereaza_in_localitate('Calafat'::TEXT,16);
CALL insereaza_in_localitate('Carei'::TEXT,40);
CALL insereaza_in_localitate('Caracal'::TEXT,15);
CALL insereaza_in_localitate('Caransebes'::TEXT,20);
CALL insereaza_in_localitate('Cavnic'::TEXT,39);
CALL insereaza_in_localitate('Calan'::TEXT,36);
CALL insereaza_in_localitate('Calarasi'::TEXT,5);
CALL insereaza_in_localitate('Calimanesti Caciulata'::TEXT,14);
CALL insereaza_in_localitate('Campeni'::TEXT,34);
CALL insereaza_in_localitate('Campia Turzii'::TEXT,33);
CALL insereaza_in_localitate('Campina'::TEXT,10);
CALL insereaza_in_localitate('Campulung'::TEXT,12);
CALL insereaza_in_localitate('Campulung Moldovenesc'::TEXT,42);
CALL insereaza_in_localitate('Cehu Silvaniei'::TEXT,32);
CALL insereaza_in_localitate('Cernavoda'::TEXT,2);
CALL insereaza_in_localitate('Chisineu Cris'::TEXT,38);
CALL insereaza_in_localitate('Cisnadie'::TEXT,35);
CALL insereaza_in_localitate('Cluj Napoca'::TEXT,33);
CALL insereaza_in_localitate('Bran'::TEXT,31);
CALL insereaza_in_localitate('Comarnic'::TEXT,10);
CALL insereaza_in_localitate('Comanesti'::TEXT,25);
CALL insereaza_in_localitate('Constanta'::TEXT,2);
CALL insereaza_in_localitate('Copsa Mica'::TEXT,35);
CALL insereaza_in_localitate('Corabia'::TEXT,15);
CALL insereaza_in_localitate('Costesti'::TEXT,12);
CALL insereaza_in_localitate('Covasna'::TEXT,28);
CALL insereaza_in_localitate('Craiova'::TEXT,16);
CALL insereaza_in_localitate('Cristuru Secuiesc'::TEXT,27);
CALL insereaza_in_localitate('Cugir'::TEXT,34);
CALL insereaza_in_localitate('Curtici'::TEXT,38);
CALL insereaza_in_localitate('Curtea de Arges'::TEXT,12);
CALL insereaza_in_localitate('Darabani'::TEXT,41);
CALL insereaza_in_localitate('Darmanesti'::TEXT,25);
CALL insereaza_in_localitate('Dealu'::TEXT,9);
CALL insereaza_in_localitate('Dej'::TEXT,33);
CALL insereaza_in_localitate('Deta'::TEXT,19);
CALL insereaza_in_localitate('Deva'::TEXT,36);
CALL insereaza_in_localitate('Dorohoi'::TEXT,41);
CALL insereaza_in_localitate('Draganesti Olt'::TEXT,15);
CALL insereaza_in_localitate('Dragasani'::TEXT,14);
CALL insereaza_in_localitate('Drobeta Turnu Severin'::TEXT,18);
CALL insereaza_in_localitate('Dumbraveni'::TEXT,35);
CALL insereaza_in_localitate('Eforie'::TEXT,2);
CALL insereaza_in_localitate('Fagaras'::TEXT,31);
CALL insereaza_in_localitate('Faget'::TEXT,19);
CALL insereaza_in_localitate('Falticeni'::TEXT,42);
CALL insereaza_in_localitate('Faurei'::TEXT,3);
CALL insereaza_in_localitate('Fetesti'::TEXT,4);
CALL insereaza_in_localitate('Fieni'::TEXT,11);
CALL insereaza_in_localitate('Filiasi'::TEXT,16);
CALL insereaza_in_localitate('Focsani'::TEXT,26);
CALL insereaza_in_localitate('Fundulea'::TEXT,5);
CALL insereaza_in_localitate('Galati'::TEXT,23);
CALL insereaza_in_localitate('Gaesti'::TEXT,11);
CALL insereaza_in_localitate('Geoagiu'::TEXT,36);
CALL insereaza_in_localitate('Gheorgheni'::TEXT,27);
CALL insereaza_in_localitate('Gherla'::TEXT,33);
CALL insereaza_in_localitate('Giurgiu'::TEXT,9);
CALL insereaza_in_localitate('Gura Humorului'::TEXT,42);
CALL insereaza_in_localitate('Hateg'::TEXT,36);
CALL insereaza_in_localitate('Harlau'::TEXT,21);
CALL insereaza_in_localitate('Harsova'::TEXT,2);
CALL insereaza_in_localitate('Horezu'::TEXT,14);
CALL insereaza_in_localitate('Huedin'::TEXT,33);
CALL insereaza_in_localitate('Hunedoara'::TEXT,36);
CALL insereaza_in_localitate('Husi'::TEXT,22);
CALL insereaza_in_localitate('Ianca'::TEXT,3);
CALL insereaza_in_localitate('Iasi'::TEXT,21);
CALL insereaza_in_localitate('Iernut'::TEXT,30);
CALL insereaza_in_localitate('Ineu'::TEXT,38);
CALL insereaza_in_localitate('Isaccea'::TEXT,1);
CALL insereaza_in_localitate('Insuratei'::TEXT,3);
CALL insereaza_in_localitate('Intorsura Buzaului'::TEXT,28);
CALL insereaza_in_localitate('Jibou'::TEXT,32);
CALL insereaza_in_localitate('Jimbolia'::TEXT,19);
CALL insereaza_in_localitate('Lehliu Gara'::TEXT,5);
CALL insereaza_in_localitate('Lipova'::TEXT,38);
CALL insereaza_in_localitate('Ludus'::TEXT,30);
CALL insereaza_in_localitate('Lugoj'::TEXT,19);
CALL insereaza_in_localitate('Lupeni'::TEXT,36);
CALL insereaza_in_localitate('Mangalia'::TEXT,2);
CALL insereaza_in_localitate('Marghita'::TEXT,37);
CALL insereaza_in_localitate('Macin'::TEXT,1);
CALL insereaza_in_localitate('Marasesti'::TEXT,26);
CALL insereaza_in_localitate('Medgidia'::TEXT,2);
CALL insereaza_in_localitate('Medias'::TEXT,35);
CALL insereaza_in_localitate('Miercurea Ciuc'::TEXT,27);
CALL insereaza_in_localitate('Mihailesti'::TEXT,9);
CALL insereaza_in_localitate('Mioveni'::TEXT,12);
CALL insereaza_in_localitate('Mizil'::TEXT,10);
CALL insereaza_in_localitate('Moinesti'::TEXT,25);
CALL insereaza_in_localitate('Moldova Noua'::TEXT,20);
CALL insereaza_in_localitate('Moreni'::TEXT,11);
CALL insereaza_in_localitate('Motru'::TEXT,17);
CALL insereaza_in_localitate('Murfatlar'::TEXT,2);
CALL insereaza_in_localitate('Nadlac'::TEXT,38);
CALL insereaza_in_localitate('Nasaud'::TEXT,29);
CALL insereaza_in_localitate('Navodari'::TEXT,2);
CALL insereaza_in_localitate('Negresti'::TEXT,22);
CALL insereaza_in_localitate('Negresti Oas'::TEXT,40);
CALL insereaza_in_localitate('Negru Voda'::TEXT,2);
CALL insereaza_in_localitate('Nehoiu'::TEXT,6);
CALL insereaza_in_localitate('Novaci'::TEXT,17);
CALL insereaza_in_localitate('Nucet'::TEXT,37);
CALL insereaza_in_localitate('Ocna Mures'::TEXT,34);
CALL insereaza_in_localitate('Ocna Sibiului'::TEXT,35);
CALL insereaza_in_localitate('Ocnele Mari'::TEXT,14);
CALL insereaza_in_localitate('Odobesti'::TEXT,26);
CALL insereaza_in_localitate('Odorheiu Secuiesc'::TEXT,27);
CALL insereaza_in_localitate('Oltenita'::TEXT,5);
CALL insereaza_in_localitate('Onesti'::TEXT,25);
CALL insereaza_in_localitate('Oradea'::TEXT,37);
CALL insereaza_in_localitate('Oravita'::TEXT,20);
CALL insereaza_in_localitate('Orastie'::TEXT,36);
CALL insereaza_in_localitate('Orsova'::TEXT,18);
CALL insereaza_in_localitate('Otopeni'::TEXT,7);
CALL insereaza_in_localitate('Otelu Rosu'::TEXT,20);
CALL insereaza_in_localitate('Ovidiu'::TEXT,2);
CALL insereaza_in_localitate('Panciu'::TEXT,26);
CALL insereaza_in_localitate('Pascani'::TEXT,21);
CALL insereaza_in_localitate('Pancota'::TEXT,38);
CALL insereaza_in_localitate('Petrila'::TEXT,36);
CALL insereaza_in_localitate('Petrosani'::TEXT,36);
CALL insereaza_in_localitate('Piatra Neamt'::TEXT,24);
CALL insereaza_in_localitate('Piatra Olt'::TEXT,15);
CALL insereaza_in_localitate('Pitesti'::TEXT,12);
CALL insereaza_in_localitate('Ploiesti'::TEXT,10);
CALL insereaza_in_localitate('Plopeni'::TEXT,10);
CALL insereaza_in_localitate('Pogoanele'::TEXT,6);
CALL insereaza_in_localitate('Predeal'::TEXT,31);
CALL insereaza_in_localitate('Pucioasa'::TEXT,11);
CALL insereaza_in_localitate('Radauti'::TEXT,42);
CALL insereaza_in_localitate('Ramnicu Sarat'::TEXT,6);
CALL insereaza_in_localitate('Ramnicu Valcea'::TEXT,14);
CALL insereaza_in_localitate('Rasnov'::TEXT,31);
CALL insereaza_in_localitate('Reghin'::TEXT,30);
CALL insereaza_in_localitate('Resita'::TEXT,20);
CALL insereaza_in_localitate('Roman'::TEXT,24);
CALL insereaza_in_localitate('Rosiori de Vede'::TEXT,13);
CALL insereaza_in_localitate('Rovinari'::TEXT,17);
CALL insereaza_in_localitate('Rupea'::TEXT,31);
CALL insereaza_in_localitate('Salonta'::TEXT,37);
CALL insereaza_in_localitate('Satu Mare'::TEXT,40);
CALL insereaza_in_localitate('Sacele'::TEXT,31);
CALL insereaza_in_localitate('Saveni'::TEXT,41);
CALL insereaza_in_localitate('Sangeorz Bai'::TEXT,29);
CALL insereaza_in_localitate('Sannicolau Mare'::TEXT,19);
CALL insereaza_in_localitate('Scornicesti'::TEXT,15);
CALL insereaza_in_localitate('Sebes'::TEXT,34);
CALL insereaza_in_localitate('Sebis'::TEXT,38);
CALL insereaza_in_localitate('Seini'::TEXT,39);
CALL insereaza_in_localitate('Segarcea'::TEXT,16);
CALL insereaza_in_localitate('Sfantu Gheorghe'::TEXT,28);
CALL insereaza_in_localitate('Sibiu'::TEXT,35);
CALL insereaza_in_localitate('Sighetu Marmatiei'::TEXT,39);
CALL insereaza_in_localitate('Sighisoara'::TEXT,30);
CALL insereaza_in_localitate('Simeria'::TEXT,36);
CALL insereaza_in_localitate('Sinaia'::TEXT,10);
CALL insereaza_in_localitate('Siret'::TEXT,42);
CALL insereaza_in_localitate('Slatina'::TEXT,15);
CALL insereaza_in_localitate('Slanic'::TEXT,10);
CALL insereaza_in_localitate('Slanic Moldova'::TEXT,25);
CALL insereaza_in_localitate('Slobozia'::TEXT,4);
CALL insereaza_in_localitate('Solca'::TEXT,42);
CALL insereaza_in_localitate('Sovata'::TEXT,30);
CALL insereaza_in_localitate('Strehaia'::TEXT,18);
CALL insereaza_in_localitate('Suceava'::TEXT,42);
CALL insereaza_in_localitate('Sulina'::TEXT,1);
CALL insereaza_in_localitate('Simleu Silvaniei'::TEXT,32);
CALL insereaza_in_localitate('Stei'::TEXT,37);
CALL insereaza_in_localitate('Talmaciu'::TEXT,35);
CALL insereaza_in_localitate('Tasnad'::TEXT,40);
CALL insereaza_in_localitate('Targoviste'::TEXT,11);
CALL insereaza_in_localitate('Targu Bujor'::TEXT,23);
CALL insereaza_in_localitate('Targu Calinesti'::TEXT,17);
CALL insereaza_in_localitate('Targu Frumos'::TEXT,21);
CALL insereaza_in_localitate('Targu Jiu'::TEXT,17);
CALL insereaza_in_localitate('Targu Lapus'::TEXT,39);
CALL insereaza_in_localitate('Targu Mures'::TEXT,30);
CALL insereaza_in_localitate('Targu Neamt'::TEXT,24);
CALL insereaza_in_localitate('Targu Ocna'::TEXT,25);
CALL insereaza_in_localitate('Targu Secuiesc'::TEXT,28);
CALL insereaza_in_localitate('Tarnaveni'::TEXT,30);
CALL insereaza_in_localitate('Techirghiol'::TEXT,2);
CALL insereaza_in_localitate('Tecuci'::TEXT,23);
CALL insereaza_in_localitate('Teius'::TEXT,34);
CALL insereaza_in_localitate('Timisoara'::TEXT,19);
CALL insereaza_in_localitate('Tismana'::TEXT,17);
CALL insereaza_in_localitate('Titu'::TEXT,11);
CALL insereaza_in_localitate('Toplita'::TEXT,27);
CALL insereaza_in_localitate('Topoloveni'::TEXT,12);
CALL insereaza_in_localitate('Tulcea'::TEXT,1);
CALL insereaza_in_localitate('Turda'::TEXT,33);
CALL insereaza_in_localitate('Turnu Magurele'::TEXT,13);
CALL insereaza_in_localitate('Tandarei'::TEXT,4);
CALL insereaza_in_localitate('Ticleni'::TEXT,17);
CALL insereaza_in_localitate('Uricani'::TEXT,36);
CALL insereaza_in_localitate('Urlati'::TEXT,10);
CALL insereaza_in_localitate('Urziceni'::TEXT,4);
CALL insereaza_in_localitate('Valea lui Mihai'::TEXT,37);
CALL insereaza_in_localitate('Vaslui'::TEXT,22);
CALL insereaza_in_localitate('Vascau'::TEXT,37);
CALL insereaza_in_localitate('Vatra Dornei'::TEXT,42);
CALL insereaza_in_localitate('Valenii de Munte'::TEXT,10);
CALL insereaza_in_localitate('Vanju Mare'::TEXT,18);
CALL insereaza_in_localitate('Victoria'::TEXT,31);
CALL insereaza_in_localitate('Videle'::TEXT,13);
CALL insereaza_in_localitate('Viseu de Sus'::TEXT,39);
CALL insereaza_in_localitate('Vlahita'::TEXT,27);
CALL insereaza_in_localitate('Vulcan'::TEXT,36);
CALL insereaza_in_localitate('Zalau'::TEXT,32);
CALL insereaza_in_localitate('Zarnesti'::TEXT,31);
CALL insereaza_in_localitate('Zimnicea'::TEXT,13);
CALL insereaza_in_localitate('Zlatna'::TEXT,34);
COMMIT;

SELECT *
FROM localitate;